backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

publish_mode: editorial_workflow
media_folder: "static/images/uploads"
public_folder: "/images/uploads"
local_backend: true

collections:
  - name: "nyheter" # Used in routes, e.g., /admin/collections/blog
    label: "nyhetsannonse" # Used in the UI
    folder: "_posts/news" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Featured Image", name: "bilde", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "comittees" # Used in routes, e.g., /admin/collections/blog
    label: "komitè" # Used in the UI
    folder: "_posts/comittees" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Topp-bilde", name: "featurd-image", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }
  - label: "sider"
    name: "pages"
    files:
      - label: "Om oss"
        name: "om-oss"
        file: "site/content/om-oss.yml"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Ingress", name: "intro", widget: "markdown" }

          - {
              label: "undertittel 'om styret'",
              name: "heading-om-styret",
              widget: "string",
            }
          - { label: "om styret", name: "body-om-styret", widget: "markdown" }
          - label: "Styremedlemmer"
            name: "boardmembers"
            widget: "list"
            fields:
              - { label: "Name", name: "navn", widget: "string" }
              - { label: "Verf", name: "position", widget: "string" }
              - {
                  label: "Om dude-en/dudeett-a/dudeett-hen",
                  name: "about-me",
                  widget: "markdown",
                }
              - { label: "bilde", name: "bilde", widget: "image" }
          - {
              label: "Skriv inn hva faen dere vil",
              name: body,
              widget: markdown,
            }

      - label: Kompendier
        name: kompendier
        file: "site/content/kompendier.yml"
        fields:
          - { label: "intro", name: "intro", widget: "markdown" }
          - label: "kompendiene"
            name: "compendiums"
            widget: "object"
            fields:
              - { label: "Tittel (fagkode...)", name: title, widget: "string" }
              - { label: "pris", name: price, widget: "number" }
              - { label: "bilde", name: "image", widget: "image" }
