backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

publish_mode: editorial_workflow
media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "nyheter" # Used in routes, e.g., /admin/collections/blog
    label: "nyhetsannonse" # Used in the UI
    folder: "_posts/news" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Layout", name: "layout", widget: "hidden", default: "news" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Bilde", name: "bilde", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "comittees" # Used in routes, e.g., /admin/collections/blog
    label: "komitè" # Used in the UI
    folder: "_posts/comittees" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., title.md
    fields: # The fields for each document, usually in front matter
      - {
          label: "Layout",
          name: "layout",
          widget: "hidden",
          default: "committee",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Topp-bilde", name: "bilde", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }
  - label: "sider"
    name: "pages"
    files:
      - label: "Om oss"
        name: "om-oss"
        file: "site/content/om-oss.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Ingress", name: "intro", widget: "markdown" }

          - {
              label: "undertittel 'om styret'",
              name: "heading-om-styret",
              widget: "string",
            }
          - { label: "om styret", name: "body-om-styret", widget: "markdown" }
          - label: "Styremedlemmer"
            name: "boardmembers"
            widget: "list"
            fields:
              - { label: "Name", name: "navn", widget: "string" }
              - { label: "Verv", name: "position", widget: "string" }
              - {
                  label: "Om dude-en/dudeett-a/dudeett-hen",
                  name: aboutme,
                  widget: markdown,
                }
              - { label: "bilde", name: "bilde", widget: "image" }
          - {
              label: "Skriv inn hva faen dere vil",
              name: body,
              widget: markdown,
            }
      - label: "Kompendier"
        name: "compendiums"
        file: "site/content/kompendier.md"
        fields:
          - { label: "intro", name: "intro", widget: "string" }
          - label: "Kompendier"
            name: "the_compendiums"
            widget: "list"
            summary: " "
            fields:
              - label: kompendie
                name: compendium
                widget: object
                fields:
                  - { label: Tittel, name: title, widget: string }
                  - {
                      label: "pris i norske kroner eller delta-coins. Dodge coins, pi-coins og andre valutaer godtas ikke",
                      name: price,
                      widget: number,
                    }
                  - { label: forsidebilde, name: cover, widget: image }
      - label: "Ny student"
        name: "newStudent"
        file: "site/content/newStudent.md"
        fields:
          - { label: alt, name: body, widget: markdown }
